In [9]:
import pandas as pd
import re
import pymorphy3

In [6]:
# df = pd.read_json("hf://datasets/UniversalCEFR/readme_ru/readme_ru.json")

In [7]:
# df = df[["text","cefr_level"]]
# df

In [5]:
data =  pd.read_json("readme_ru.json")
data

                                                   text cefr_level
0     А если это только сон, остаточное сновиденье, ...         C2
1     И стерженек мой, сникнув от жары, едва карябае...         B2
2     Это я про себя бормочу, на исходе августа соби...         B1
3     в инобытие, и сущее, письменный смешав гранит,...         C1
4     Хлопнет, взревет ― и в дыму с концами я потеря...         C1
...                                                 ...        ...
1753  Я бы отдал весь свой гений и все свои книги за...         B1
1754  Любить… но кого же?.. на время — не стоит труд...         B1
1755  Вещи усиливают ощущение времени. Часто они жив...         B1
1756  Мы не столько любим людей за то добро, которое...         A1
1757  Доброму человеку бывает стыдно даже перед соба...         A1

[1758 rows x 2 columns]

In [19]:
tokens = []

for text in data["text"]:
    token = re.findall(r"\b\w+\b",text.lower())
    tokens.append(token)

# tokens = re.findall(r"\b\w+\b",data["text"])
data["tokens"] = tokens
data

,text,cefr_level,tokens
0,"А если это только сон, остаточное сновиденье, ...",C2,"[а, если, это, только, сон, остаточное, сновид..."
1,"И стерженек мой, сникнув от жары, едва карябае...",B2,"[и, стерженек, мой, сникнув, от, жары, едва, к..."
2,"Это я про себя бормочу, на исходе августа соби...",B1,"[это, я, про, себя, бормочу, на, исходе, авгус..."
3,"в инобытие, и сущее, письменный смешав гранит,...",C1,"[в, инобытие, и, сущее, письменный, смешав, гр..."
4,"Хлопнет, взревет ― и в дыму с концами я потеря...",C1,"[хлопнет, взревет, и, в, дыму, с, концами, я, ..."
...,...,...,...
1753,Я бы отдал весь свой гений и все свои книги за...,B1,"[я, бы, отдал, весь, свой, гений, и, все, свои..."
1754,Любить… но кого же?.. на время — не стоит труд...,B1,"[любить, но, кого, же, на, время, не, стоит, т..."
1755,Вещи усиливают ощущение времени. Часто они жив...,B1,"[вещи, усиливают, ощущение, времени, часто, он..."
1756,"Мы не столько любим людей за то добро, которое...",A1,"[мы, не, столько, любим, людей, за, то, добро,..."
1757,Доброму человеку бывает стыдно даже перед соба...,A1,"[доброму, человеку, бывает, стыдно, даже, пере..."

In [ ]:
morph = pymorphy3.MorphAnalyzer()
lemas = []
for token in data["tokens"]:
    lemma = morph.parse(token).normal